---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - stacknet
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    volumes:
      - /var/lib/flaresolver:/config
    networks:
      - stacknet
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/radarr:/config
      - ${DATA_VOLUME}/data:/data
    ports: 
      - 7878:7878
    networks:
      - stacknet
    extra_hosts:
      - "qbittorrent:172.17.0.1"  # allows us of 'qbittorrent' as hostname
    restart: unless-stopped 

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/sonarr:/config
      - ${DATA_VOLUME}/data:/data
    ports:
      - 8989:8989
    networks:
      - stacknet
    extra_hosts:
      - "qbittorrent:172.17.0.1"  # allows use of 'qbittorrent' as hostname
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./appdata/qbittorrent:/config
      - ${DATA_VOLUME}/data:/data
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    # networks:
    #   - stacknet
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/jellyfin:/config
      - ${DATA_VOLUME}/data:/data
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - stacknet
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/jellyseerr:/app/config
    ports:
      - 5055:5055
    networks:
      - stacknet
    restart: unless-stopped

networks:
  stacknet:
    external: true
