---
services:
  #######################
  # PROWLARR 
  #######################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  #######################
  # RADARR 
  #######################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/radarr:/config
      - ${DATA_VOLUME}/media/movies:/movies #optional
      - ${DATA_VOLUME}/torrents/movies:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped 

  #######################
  # SONARR 
  #######################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/sonarr:/config
      - ${DATA_VOLUME}/media/tv:/tv #optional
      - ${DATA_VOLUME}/torrents/tv:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  #######################
  # QBITTORRENT 
  #######################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./appdata/qbittorrent:/config
      - ${DATA_VOLUME}/torrents:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  #######################
  # JELLYFIN 
  #######################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/jellyfin:/config
      - ${DATA_VOLUME}/media:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
